[package]
name = "noise"
version = "0.1.0"
authors = ["Duncan McGreggor <duncan@cnbb.games>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/hexagram30/noise"

[lib]
name = "hxgm30noise"

[dependencies]
noise = "0.6.0"

[[example]]
name = "caves"
