[package]
name = "hxgm30-noise"
version = "0.2.0"
authors = ["Duncan McGreggor <duncan@cnbb.games>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/hexagram30/noise"

[lib]
name = "hxgm30noise"

[dependencies]
clap = "2.33.0"
clap_derive = { git = "https://github.com/clap-rs/clap_derive", optional = true }
log = "0.4.8"
noise = "0.6.0"
twyg = "0.1.3"

[[example]]
name = "caves"
