[package]
name = "noise"
version = "0.1.0"
authors = ["Duncan McGreggor <duncan@cnbb.games>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "0.6.0"