[package]
name = "hxgm30-noise"
description = "Noise-generation for use in hexagram30 projects"
version = "0.2.0"
authors = ["Duncan McGreggor <duncan@cnbb.games>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/hexagram30/noise"

[lib]
name = "hxgm30noise"

[dependencies]
clap = "2.33"
log = "0.4.8"
noise = "0.6.0"
twyg = "0.1.7"

[[example]]
name = "caves"
